# Generated by Django 4.2 on 2023-04-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auction_listing_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='list_bid',
            field=models.ManyToManyField(blank=True, related_name='bids', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auctions.auction_listing'),
        ),
    ]
