# Generated by Django 4.2 on 2023-04-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
